refactor_books:
    path:  /books
    defaults: { _controller: ApplicationRefactorReferenceBundle:Book:index}
refactor_show_books:
    path:  /books/show/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:Book:show}
    requirements:
        id:  \d+
refactor_add_books:
    path:  /books/add/
    defaults: { _controller: ApplicationRefactorReferenceBundle:Book:add}
refactor_edit_books:
    path:  /books/edit/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:Book:edit}
    requirements:
        id:  \d+
refactor_remove_books:
    path:  /books/remove/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:Book:remove}
    requirements:
        id:  \d+


refactor_projects:
    path:  /projects/{sort}
    defaults: { _controller: ApplicationRefactorReferenceBundle:Fiche:index, sort: null}
refactor_show_projects:
    path:  /projects/show/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:Fiche:show}
    requirements:
        id:  \d+
refactor_add_projects:
    path:  /projects/add/
    defaults: { _controller: ApplicationRefactorReferenceBundle:Fiche:add}
refactor_edit_projects:
    path:  /projects/edit/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:Fiche:edit}
    requirements:
        id:  \d+
refactor_remove_projects:
    path:  /projects/remove/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:Fiche:remove}
    requirements:
        id:  \d+

refactor_tags:
    path: /tags
    defaults: { _controller: ApplicationRefactorReferenceBundle:Tag:index }
refactor_tags_add:
    path:  /tags/add/
    defaults: { _controller: ApplicationRefactorReferenceBundle:Tag:add }

refactor_tags_edit:
    path:  /tags/edit/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:Tag:edit}
    requirements:
        id:  \d+
refactor_tags_remove:
    path:  /tags/remove/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:Tag:remove}
    requirements:
        id:  \d+

refactor_medias:
    path:  /medias/
    defaults: { _controller: ApplicationRefactorReferenceBundle:Media:index}
refactor_add_medias:
    path:  /medias/add
    defaults: { _controller: ApplicationRefactorReferenceBundle:Media:add}
refactor_edit_medias:
    path:  /medias/edit/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:Media:edit}
    requirements:
        id:  \d+
refactor_remove_medias:
    path:  /medias/remove/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:Media:remove}
    requirements:
        id:  \d+

refactor_pdf_projects:
    path:  /pdf/project/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:PDF:project}
refactor_get_pdf_projects:
    path:  /get/pdf/project/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:PDF:projectPDF}
refactor_pdf_books:
    path:  /pdf/book/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:PDF:book}
refactor_get_pdf_books:
    path:  /get/pdf/book/{id}
    defaults: { _controller: ApplicationRefactorReferenceBundle:PDF:bookPDF}
